- name: test-playbook
  hosts: localhost
  become: yes
  vars:
    new_user: "brickdev"
    new_pass: "pass"
    ssh_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDW1sg+ys6EEZd6ZzbDlrMMybOBUALEtERY2/ZKsvgbcAzTERxbtsqu+iNNDBo+sf3L3YuWkd8fLH4SJ3MQV42ySc6ml2tMT0G2r+QIWwFz+nPaD2DY8blgFpsa41TZxwKgLmqEtUVlps9Q6Un5KtJMjTl2MWYKswdxSqHw8em0DNigJolWfzsmoTvd1HXTYdj/PiJECW3nS38PFlL19Av6ipwrbxme2/VyvjolX5F3p/dgLkuUU7UMQ+tlx9gAlN0F/Tf6zMHSubIBC7lOf58zP+IlykdD4leVaNpFckk9hxnKCZpyM7jlwi2YSnYLAOh4v56NTq7c/yG2jX9+lSb"
  tasks:
    - name: create new user
      user:
        name: "{{ new_user }}"
        password: "{{ new_pass }}"
        state: present
        shell: /bin/bash
    - name: copy ssh pubkey for the cloudru user
      copy:
        dest: /home/cloudru/.ssh/authorized_keys
        content: "{{ ssh_pubkey }}"
        mode: '0600'
        owner: cloudru
        group: cloudru
    - name: allow pubkey ssh authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
    - name: disable root ssh connection
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
    - name: restart sshd
      service:
        name: sshd
        state: restarted
